\input texinfo  @c -*-texinfo-*-

@documentencoding UTF-8

@ifnottex
@macro smallskip{}
@vskip 6pt
@end macro

@macro medskip{}
@vskip 12pt
@end macro

@macro bigskip{}
@vskip 24pt
@end macro
@end ifnottex

@macro EquationMark{}
@html
<!-- EquationMark -->
@end html
@end macro

@macro ScreenShot{f}
@center @image{\f\, 5in}
@end macro

@macro ReleaseDate{}
June 2024
@end macro

@exampleindent 2

@c start of header
@setfilename pdfmorph
@settitle PDFmorph, release 1.0, @ReleaseDate{}
@c end of header

@c Part 1: copying
@copying
Copyright 2009-2024, Board of Trustees of Columbia University in the city of New York.
@end copying

@c Part 2: title
@titlepage

@title PDFmorph user guide
@subtitle 1.0 release
@subtitle @ReleaseDate{}
@author C. L. Farrow, C. J. Wright, P. Juhás, C.-H. Liu, T. Davis,
@author S. M. Román, A. Yang, and S. J. L. Billinge

@page
@vskip 0pt plus 1filll
@c @insertcopying

@ifhtml
@node acknowledgments
@end ifhtml
@heading Acknowledgments
@cindex  acknowledgments
@include acknowledgements.texinfo


@page
@vskip 0pt plus 1filll
@majorheading Preface
@heading Redistribution
@include redistribution.texinfo


@heading Disclaimer
@include disclaimer.texinfo

@end titlepage


@c Part 3: content
@contents


@c Make menu if html
@ifhtml

@node Top
@top


@menu
* Introduction::
* Installation::
* Tutorials::
* Available morphs::
* PDFmorph options::
* Index::
@end menu

@end ifhtml

@page
@vskip 0pt plus 1filll
@node    Introduction, Installation, Top, Top
@chapter Introduction
@cindex  introduction

PDFmorph is a Python package that increases the insight researchers can
obtain from measured atomic pair distribution functions (PDFs) in a 
model-independent way. It was originally designed to help a researcher
answer a question: "Has my material undergone a phase transition between
these two measurements?"

@page
@vskip 0pt plus 1filll
@node    Installation, Tutorials, Introduction, Top
@chapter Installation
@cindex  installation

@menu
* Availability::
* Requirements::
* Installation instructions::
@end menu

@node    Availability, Requirements, Installation, Installation
@section Availability
@cindex  availability

PDFmorph is open source and distributed under the BSD license. 
It runs on Windows, Mac OS, Linux, and all major Unix systems.
The source code is freely available at @url{https://github.com/diffpy/diffpy.pdfmorph}.

@node    Requirements, Installation instructions, Availability, Installation
@section Requirements
@cindex  requirements

PDFmorph is currently run from the command line, so it is recommended that users
first familiarize themselves with their operating system's command line interface.

PDFmorph currently requires Python 3.10 or higher to run. It also makes use of
the following third party libraries:
@itemize @bullet
@item @url{https://numpy.org/, NumPy} - Python's fast scientific computing library
@item @url{https://matplotlib.org/, Matplotlib} - Python plotting library
@item @url{https://scipy.org/, SciPy} - Python's technical computing library
@item @url{https://www.diffpy.org/diffpy.utils/, diffpy.utils} 
- @url{https://www.diffpy.org/, DiffPy} general utility functions
@end itemize
These dependencies will be installed automatically if you use the conda installation
procedure described in the following section (@ref{Installation instructions}).

@node    Installation instructions, , Requirements, Installation
@section Installation instructions
@cindex  installationinstrunctions

We recommend installing the package and its dependencies using conda.
Miniconda, a minimal installer for conda, can be downloaded
@url{https://docs.anaconda.com/free/miniconda/, here}. 
Once Miniconda is installed, run @code{conda} on the command line
 to test that it has been installed properly.

To create and activate a conda environment to use PDFmorph, run the following command.
@example
conda create -n pdfmorph_env python=3 --yes
conda activate pdfmorph_env
@end example

A conda environment must be active to use the packages within.
In future sessions, make sure to run @code{conda activate pdfmorph_env} to activate the
environment before interacting with the PDFmorph program.

Once active, you can install PDFmorph into your environment from the
@url{https://conda-forge.org/, conda-forge} channel of Anaconda packages by running
@example
conda config --add channels conda-forge
conda install diffpy.pdfmorph
@end example
This installation only needs to be done once. The next time you activate the environment,
these packages will already be installed.

When you are finished with the session, exit the environment by running
@example
conda deactivate pdfmorph_env
@end example

If you do not wish to use conda to install, PDFmorph is also available on the
@url{https://pypi.org/, Python Package Index} or can be installed from source
at @url{https://github.com/diffpy/diffpy.pdfmorph}. Note that these installation
methods will require you to first install the dependencies listed in the previous section
(@ref{Requirements}).

@page
@vskip 0pt plus 1filll
@node    Tutorials, Available morphs, Installation, Top
@chapter Tutorials
@cindex  tutorials

@menu
* Quick start tutorial::
* Extra tutorials::
@end menu

This section includes a quick tutorial to acquaint users with PDFmorph.
Also included are a few extra tutorials covering some more specific PDFmorph functionalities.

Before you start this tutorial, make sure you have installed all necessary software
and dependencies (@ref{Installation instructions}).

@node    Quick start tutorial, Extra tutorials, Tutorials, Tutorials
@section Quick start tutorial
@cindex  quickstarttutorial

@node    Extra tutorials, , Quick start tutorial, Tutorials
@section Extra tutorials
@cindex  extratutorials

@page
@vskip 0pt plus 1filll
@node    Available morphs, PDFmorph options, Quick start tutorial, Top
@chapter Available morphs
@cindex  availablemorphs

In this section, we detail a few use-cases for morphs.

@page
@vskip 0pt plus 1filll
@node    PDFmorph options, Index, Available morphs, Top
@chapter PDFmorph options
@cindex  pdfmorphoptions

Explaination of options

@c End TexInfo file
@node Index, Top
@unnumbered Index

@printindex cp

@bye
